[package]
name = "gift-cards"
version = "0.5.0"
authors = ["Angel Ventures LLC"]
edition = "2021"
license = "GPL-3.0-or-later"

exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "contract.wasm",
  "hash.txt",
]

[lib]
crate-type = ["cdylib", "rlib"]
name = "gift_cards"

[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all instantiate/execute/query exports
library = []

[dependencies]
cw20 = "1.1.0"
cosmwasm-std = "1.3.3"
cosmwasm-schema = "1.3.3"
cw-storage-plus = "1.1.0"
cw-asset = "3.0.0"
schemars = "0.8.10"
serde = { version = "1.0.145", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.31" }

[dev-dependencies]
