[package]
name = "halo-vesting"
version = "0.0.1"
authors = ["Angel Ventures LLC"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all init/handle/query exports
library = []

[dependencies]
cw20 = { version = "0.8.0" } 
cosmwasm-std = { version = "0.16.0", features = ["iterator"] }
cosmwasm-storage = { version = "0.16.0", features = ["iterator"] }
cw-storage-plus = { version = "0.9.0" }
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
halo-token = { version = "0.1.0", path = "../../../packages/halo_token" }

[dev-dependencies]
cosmwasm-schema = { version = "0.16.0", default-features = false  }
