[workspace]
members = [
    "packages/angel_core",
    "packages/halo_token",
    "packages/cw900",
    "contracts/core/registrar",
    "contracts/core/index-fund",
    "contracts/normalized-endowment/accounts",
    "contracts/halo/airdrop",
    "contracts/multisig/cw4-group",
    "contracts/multisig/cw3-multisig",
]

exclude = [
    "contracts/vaults/anchor",
    "contracts/normalized-endowment/cw900-lv",
    "contracts/normalized-endowment/dao",
    "contracts/normalized-endowment/dao-token",
    "contracts/normalized-endowment/donation-match",
    "contracts/normalized-endowment/fee-distributor",
    "contracts/halo/collector",
    "contracts/halo/community",
    "contracts/halo/distributor",
    "contracts/halo/gov",
    "contracts/halo/gov-hodler",
    "contracts/halo/staking",
    "contracts/halo/vesting",
]

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true
