[workspace]
members = [
    "packages/angel_core",
    "packages/angel_portal",
    "contracts/core/*",
    "contracts/portal/*",
]

exclude = []

[profile.release]
rpath = false
lto = true
overflow-checks = true
