[workspace]
members = [
    "packages/angel_core",
    "packages/halo_token",
    "packages/halo_lbp",
    "packages/halo_amm",
    "contracts/core/*",
    "contracts/vaults/anchor",
    "contracts/guardian-angels/*",
    "contracts/halo/*",
    "contracts/lbp/*",
    "contracts/amm/*",
]

exclude = []

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true
