[workspace]
members = [
    "packages/angel_core",
    "packages/halo_token",
    "contracts/core/accounts",
    "contracts/core/index-fund",
    "contracts/core/registrar",
    "contracts/vaults/anchor",
    "contracts/governance/cw4-group",
    "contracts/governance/guardians-cw3",
    "contracts/governance/guardians-cw4",
    "contracts/governance/ap-team-cw3",
    "contracts/halo/airdrop",
    "contracts/halo/collector",
    "contracts/halo/community",
    "contracts/halo/distributor",
    "contracts/halo/gov",
    "contracts/halo/gov-hodler",
    "contracts/halo/staking",
    "contracts/halo/vesting",
]

exclude = []

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true
