[workspace]
members = [
    "packages/angel_core",
    "contracts/core/accounts",
    "contracts/core/index-fund",
    "contracts/core/registrar",
]

exclude = [
    "packages/angel_portal",
    "contracts/portal/portal-template",
]

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true
