[workspace]
members = [
    "packages/angel_core",
    "packages/halo_token",
    "packages/haloswap",
    "contracts/core/accounts",
    "contracts/core/index-fund",
    "contracts/core/registrar",
    "contracts/vaults/anchor",
    "contracts/guardian-angels/cw4-group",
    "contracts/guardian-angels/guardian-angels-cw3",
    "contracts/guardian-angels/ap-team-cw3",
    "contracts/halo/airdrop",
    "contracts/halo/collector",
    "contracts/halo/community",
    "contracts/halo/distributor",
    "contracts/halo/gov",
    "contracts/halo/staking",
    "contracts/halo/vesting",
    "contracts/haloswap/haloswap_factory",
    "contracts/haloswap/haloswap_router",
    "contracts/haloswap/haloswap_pair",
    "contracts/haloswap/haloswap_token",
]

exclude = []

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true
