[workspace]
members = [
    "packages/angel_core",
    "contracts/core/accounts",
    "contracts/core/index-fund",
    "contracts/core/registrar",
    "contracts/vaults/anchor",
    "contracts/guardian-angels/cw4-group",
    "contracts/guardian-angels/guardian-angels-cw3",
    "contracts/guardian-angels/ap-team-cw3",
]

exclude = []

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true
