[package]
name = "angel-core"
version = "0.1.2"
authors = ["Angel Ventures LLC"]
edition = "2018"

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-bignumber = "2.2.0"
cosmwasm-std = { version = "0.16.0" }
cw20 = "0.9.0"
cw4 = "0.9.0"
schemars = "0.8.1"
serde = { version = "1.0.125", default-features = false, features = ["derive"] }
terra-cosmwasm = "2.2.0"
thiserror = { version = "1.0.24" }

[dev-dependencies]
cosmwasm-schema = { version = "0.16.0" }
