[package]
name = "angel-core"
version = "0.1.2"
authors = ["Angel Ventures LLC"]
edition = "2018"

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-std = "1.0.0"
cw20 = "0.14.0"
cw3 = "0.14.0"
cw4 = "0.14.0"
cw-utils = "0.14.0"
schemars = "0.8.1"
serde = { version = "1.0.125", default-features = false, features = ["derive"] }
thiserror = "1.0.24"
cw-asset = "2.2.0"
cw20-base = { version = "0.13.4", features = ["library"] }

[dev-dependencies]
cosmwasm-schema = "1.0.0"
