[package]
name = "halo-token"
version.workspace = true
authors.workspace = true
edition.workspace = true
licence.workspace = true
description = "Common helpers for other angel-token specs"
metadata = {}

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all instantiate/execute/query exports
library = []

[dependencies]
cw20 = "1.0.1"
cosmwasm-std = "1.2.1"
cosmwasm-schema = "1.2.1"
cosmwasm-storage = "1.2.1"
cw-asset = "3.0.0"
cw-utils = "1.0.0"
cw-controllers = "1.0.1"
