[package]
name = "accounts"
version = "2.0.3"
authors.workspace = true
edition.workspace = true

exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "contract.wasm",
  "hash.txt",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]
name = "accounts"

[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
angel-core = { path = "../../../packages/angel_core" }

cw2 = "1.0.1"
cw20 = "1.0.1"
cw4 = "1.0.1"
cosmwasm-std = "1.2.1"
cosmwasm-schema = "1.2.1"
cosmwasm-storage = "1.2.1"
cw-storage-plus = "1.0.1"
cw-asset = "3.0.0"
cw-utils = "1.0.0"

schemars = "0.8.10"
serde = { version = "1.0.145", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.31" }

ethabi = { version = "18.0.0", default-features = false, features = [] }
prost = {version = "0.11.2", default-features = false, features = ["prost-derive"]}
serde-json-wasm = "0.5.0"
osmosis-std-derive = "0.13.2"
osmosis-std = "0.14.0"

[dev-dependencies]
