[package]
name = "halo-token"
version = "2.0.0"
authors = ["Angel Ventures LLC"]
edition = "2018"
description = "Common helpers for other angel-token specs"
license = "Apache-2.0"
metadata = {}

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cw-utils = "0.13.2"
cw20 = "0.13.2"
cw-asset = "2.0.0"
cosmwasm-std = "1.0.0"
cosmwasm-storage = "1.0.0"
cw-controllers = "0.13.2"
schemars = "0.8.10"
serde = "1.0.137"

[dev-dependencies]
cosmwasm-schema = { version = "1.0.0" }