[package]
name = "ve-token"
version = "1.0.0"
authors.workspace = true
edition.workspace = true
licence.workspace = true
description = "A curve style ve token for Angel Protocol Endowments"

exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "contract.wasm",
  "hash.txt",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
angel-core = { path = "../../../packages/angel_core" }

cw20 = "1.0.1"
cosmwasm-std = "1.2.1"
cosmwasm-schema = "1.2.1"
cosmwasm-storage = "1.2.1"
cw-storage-plus = "1.0.1"

schemars = "0.8.10"
serde = { version = "1.0.145", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.31" }

[dev-dependencies]
