[package]
name = "cw900"
version = "1.0.0"
authors = ["Angel Ventures LLC"]
edition = "2018"
description = "Common helpers for Glow protocol"
license = "Apache-2.0"
repository = ""
homepage = "https://glowyield.com"
documentation = "https://docs.glowyield.com"
metadata = {}

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cw-utils = "0.13.2"
cw20 = "0.13.2"
cosmwasm-std = "1.0.0"
cosmwasm-storage = "1.0.0"
schemars = "0.8.10"
serde = "1.0.137"

[dev-dependencies]
cosmwasm-schema = { version = "1.0.0" }