[package]
name = "portal_anchor"
version = "0.1.0"
authors = ["Angel Ventures LLC"]
edition = "2018"

exclude = [
    # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
    "contract.wasm",
    "hash.txt",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true

[profile.dev]
overflow-checks = true

[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
angel-core = { version = "0.1.0", path = "../../../packages/angel_core" }
angel-portals = { version = "0.1.0", path = "../../../packages/angel_portals" }
cw20 = "0.8.0-rc2"
cw-controllers = "0.8.0-rc2"
cw20-base = { version = "0.8.0-rc2", features = ["library"] }
cosmwasm-std = { version = "0.16.0", features = ["staking"] }
cosmwasm-storage = { version = "0.16.0", features = ["iterator"] }
cosmwasm-bignumber = "2.2.0"
cw-storage-plus = { version = "0.8.0-rc2", features = ["iterator"] }
schemars = "0.8.1"
serde = { version = "1.0.125", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.24" }
terraswap = "2.4.0"
terra-cosmwasm = "2.2.0"

[dev-dependencies]
cosmwasm-schema = { version = "0.16.0" }
