[package]
name = "halo-lbp"
version = "0.1.0"
authors = ["Angel Ventures LLC"]
edition = "2018"
description = "Common halo-lbp types"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cw20 = { version = "0.8" }
terra-cosmwasm = { version = "2.2.0" }
cosmwasm-std = { version = "0.16.0", features = ["iterator"] }
cw-storage-plus = {version = "0.8.0", features = ['iterator']}
schemars = "0.8"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
uint = "0.9.1"

[dev-dependencies]
cosmwasm-schema = "0.16.1"