[package]
name = "angel-portal"
version = "0.1.0"
authors = ["Angel Ventures LLC"]
edition = "2018"

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cw2 = "0.7.0"
cw20 = "0.7.0"
cw-controllers = "0.7.0"
cw20-base = { version = "0.7.0", features = ["library"] }
cosmwasm-std = { version = "0.15.0" }
cw-storage-plus = { version = "0.7.0", features = ["iterator"] }
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.23" }

[dev-dependencies]
cosmwasm-schema = { version = "0.15.0" }
