[package]
name = "halo-vesting"
version = "2.0.0"
authors = ["Angel Ventures LLC"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all init/handle/query exports
library = []

[dependencies]
halo-token = { path = "../../../packages/halo_token" }

cw20 = "1.0.1"
cosmwasm-std = "1.2.1"
cosmwasm-storage = "1.2.1"
cw-storage-plus = "1.0.1"

schemars = "0.8.10"
serde = { version = "1.0.145", default-features = false, features = ["derive"] }

[dev-dependencies]
cosmwasm-schema = "1.2.1"
