[package]
name = "halo-vesting"
version = "2.0.0"
authors.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]
name = "halo_vesting"

[features]
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all init/handle/query exports
library = []

[dependencies]
halo-token = { path = "../../../packages/halo_token" }

cw20 = "1.1.0"
cosmwasm-std = "1.3.3"
cosmwasm-schema = "1.3.3"
cosmwasm-storage = "1.2.1"
cw-storage-plus = "1.1.0"

schemars = "0.8.10"
serde = { version = "1.0.145", default-features = false, features = ["derive"] }

[dev-dependencies]
