name: Rust

on:
  push:
    branches: [ main, RC-v2 ]
  pull_request:
    branches: [ main, RC-v2 ]

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    working-directory: ./cosmwasm

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - nightly
    steps:
    - name: Run cargo test
    - run: cargo test --verbose