name: Rust

on:
  push:
    branches: [ main, RC-v2 ]
  pull_request:
    branches: [ main, RC-v2 ]

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    working-directory: ./cosmwasm

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - nightly
    steps:
    - uses: actions/checkout@v3
    - name: Run cargo-tarpaulin
      uses: actions-rs/tarpaulin@v0.1
      with:
        version: latest
        args: '-- --test-threads 1'
