name: Rust

on:
  push:
    branches: [ main ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    working-directory: ./cosmwasm

jobs:
  build-n-test:
    name: "Build wasms & run unit-tests"
    runs-on: ubuntu-latest
    environment: production
    strategy:
      matrix:
        toolchain:
          - nightly
    steps:
      - uses: actions/checkout@v3
      - name: Build the contracts code
        run: cargo build --verbose
      - name: Run tests for contracts
        run: cargo test --verbose
