name: Rust

on:
  push:
    branches: [ main, RC-v2 ]
  pull_request:
    branches: [ main, RC-v2 ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - nightly
    steps:
    - uses: actions/checkout@v3
    - name: Run cargo-tarpaulin
      working-directory: ./cosmwasm
      uses: actions-rs/tarpaulin@v0.1
      with:
        version: '0.15.0'
        args: '-- --test-threads 1'
