name: Rust

on:
  push:
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    working-directory: ./cosmwasm

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - nightly
    steps:
      - uses: actions/checkout@v3
      - name: Build the contracts code
        run: cargo build --verbose
      - name: Run tests for contracts
        run: cargo test --verbose
